# ==============================================================================
# Cloudflare Pages / Wrangler Configuration File
# ==============================================================================

name = "dashboard-der"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-23"

[vars]
API_SECRET_TOKEN = "f3b9c4501a2d4807a9e3a6c9d2f5e70c"

[[d1_databases]]
binding = "DASHBOARD_DB"
database_name = "dashboard-db"
database_id = "fcb3b2d5-ce78-4881-bbe7-2e6df85c75f8"
