# ==============================================================================
# Cloudflare Pages / Wrangler Configuration File
# ==============================================================================

name = "dashboard"
compatibility_date = "2026-05-23"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "DASHBOARD_KV"
id = "7fa42ae0bfaf47938990ad8194e5c61c"
